apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tryonmagic
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Project for tryonmagic applications"

  sourceRepos:
    - 'https://github.com/tryonmagic/**'

  destinations:
    - name: '*'
      namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  roles:
    - name: admin
      description: "Full admin access to tryonmagic project ONLY"
      policies:
        - p, proj:tryonmagic:admin, applications, get, tryonmagic/*, allow
        - p, proj:tryonmagic:admin, applications, sync, tryonmagic/*, allow
        - p, proj:tryonmagic:admin, applications, update, tryonmagic/*, allow

  orphanedResources:
    warn: true