apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tryonmagic
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Project for tryonmagic applications"

  sourceRepos:
    - 'https://github.com/tryonmagic/**'

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  roles:
    - name: admin
      description: "Full admin access to tryonmagic project ONLY"
      policies:
        - p, proj:tryonmagic:admin, applications, *, tryonmagic/*, allow
        - p, proj:tryonmagic:admin, projects, get, tryonmagic, allow
      groups:
        - mail@timam.dev

  orphanedResources:
    warn: true