apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tryonmagic
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Project for tryonmagic applications"

  sourceRepos:
    - 'https://github.com/tryonmagic/*'  # All tryonmagic repositories
    - 'https://charts.bitnami.com/bitnami'
    # Add more specific repos as needed, avoid '*' for better security

  # Define which Kubernetes clusters this project can deploy to
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc  # Local cluster

  # Define which Kubernetes resources this project can manage
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'apiextensions.k8s.io'
      kind: CustomResourceDefinition
    - group: 'networking.k8s.io'
      kind: IngressClass

  # Define which namespaced resources this project can manage
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'  # Allow all core resources (pods, services, configmaps, etc.)
    - group: 'apps'
      kind: '*'  # Allow all apps resources (deployments, statefulsets, etc.)
    - group: 'networking.k8s.io'
      kind: '*'  # Allow ingress, network policies, etc.
    - group: 'cert-manager.io'
      kind: '*'  # If using cert-manager
    - group: 'traefik.containo.us'
      kind: '*'  # If using Traefik CRDs

  # Project roles - These roles are LIMITED TO THIS PROJECT ONLY
  roles:
    # Project Admin - full access to tryonmagic project ONLY
    - name: admin
      description: "Full admin access to tryonmagic project ONLY"
      policies:
        - p, proj:tryonmagic:admin, applications, *, tryonmagic/*, allow
        - p, proj:tryonmagic:admin, repositories, *, *, allow
        - p, proj:tryonmagic:admin, certificates, *, *, allow
        - p, proj:tryonmagic:admin, clusters, get, *, allow
        - p, proj:tryonmagic:admin, exec, create, */*, allow

      jwtTokens:
        - iat: 1640995200

    # Project Developer - can deploy and manage applications in tryonmagic project ONLY
    - name: developer
      description: "Developer access - can manage applications in tryonmagic project ONLY"
      policies:
        - p, proj:tryonmagic:developer, applications, *, tryonmagic/*, allow
        - p, proj:tryonmagic:developer, repositories, get, *, allow
        - p, proj:tryonmagic:developer, clusters, get, *, allow

    # Project Viewer - read-only access to tryonmagic project ONLY
    - name: viewer
      description: "Read-only access to tryonmagic project ONLY"
      policies:
        - p, proj:tryonmagic:viewer, applications, get, tryonmagic/*, allow
        - p, proj:tryonmagic:viewer, repositories, get, *, allow
        - p, proj:tryonmagic:viewer, clusters, get, *, allow

  # Sync windows
  syncWindows:
    - kind: allow
      schedule: '* * * * *'  # Always allow
      duration: 24h
      applications:
        - '*'

