apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tryonmagic
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Project for tryonmagic applications with GitHub OIDC authentication"

  sourceRepos:
    - 'https://github.com/tryonmagic/**'

  # Define which Kubernetes clusters this project can deploy to
  destinations:
    - namespace: '!kube-system'
      server: https://kubernetes.default.svc  # Local cluster

  # TODO: implement clusterResourceWhitelist namespaceResourceWhitelist

  # Project roles - These roles are LIMITED TO THIS PROJECT ONLY
  roles:
    # Project Admin - full access to tryonmagic project ONLY
    - name: admin
      description: "Full admin access to tryonmagic project ONLY"
      policies:
        - p, proj:tryonmagic:admin, applications, *, *, allow
      groups:
        - user@example.org

  orphanedResources:
    warn: true