apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tryonmagic
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Project for tryonmagic applications"

  sourceRepos:
  - 'https://github.com/tryonmagic/**'
  - 'https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts'
  - 'https://aws.github.io/secrets-store-csi-driver-provider-aws'
  - 'https://github.com/kubernetes-sigs/secrets-store-csi-driver/charts'

  destinations:
  - name: '*'
    namespace: '*'
    server: https://k8s.tryonmagic.com:6443

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  roles:
  - name: admin
    description: "Full admin access to tryonmagic project ONLY"
    policies:
      - p, proj:tryonmagic:admin, applications, *, */*, allow
      - p, proj:tryonmagic:admin, logs, *, */*, allow
