# argocd-install/values.yaml
# ArgoCD configuration with GitHub OAuth authentication
global:
  # Global configuration
  domain: hobbydeployer.timam.dev

configs:
  # ArgoCD Server configuration
  cm:
    dex.config: |
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: Iv23lizfmHBuKOJubMiZ
          clientSecret: 59ddfdfb672541c91193917c69229d7360019926
          orgs:
          - name: tryonmagic
            teams:
            - all
          # Optional: Restrict to specific organizations
          # orgs:
          # - name: your-github-org
          #   teams:
          #   - developers
          #   - admins

    # URL configuration
    url: https://hobbydeployer.timam.dev

    # Application instance label key
    application.instanceLabelKey: argocd.argoproj.io/instance

    # Default user policy - no permissions by default for OAuth users
    policy.default: role:readonly

    # RBAC policy configuration
    policy.csv: |
      # ArgoCD admin user - full admin permissions
      p, role:admin, applications, *, */*, allow
      p, role:admin, clusters, *, *, allow
      p, role:admin, repositories, *, *, allow
      p, role:admin, certificates, *, *, allow
      p, role:admin, accounts, *, *, allow
      p, role:admin, gpgkeys, *, *, allow
      p, role:admin, logs, *, *, allow
      p, role:admin, exec, *, */*, allow
      p, role:admin, projects, *, *, allow
      
      # Assign admin role to built-in admin user
      g, admin, role:admin
      
      # Default policy - no access by default for OAuth users
      p, role:readonly, applications, get, */*, deny
      p, role:readonly, clusters, get, *, deny
      p, role:readonly, repositories, get, *, deny
      
      # GitHub user 'timam' gets admin access to tryonmagic project only
      # The format is: g, <github-username>, <role>
      g, timam, proj:tryonmagic:admin

  # ArgoCD RBAC configuration
  rbac:
    # RBAC policy with GitHub integration and admin permissions
    policy.csv: |
      # Built-in admin user - full system admin permissions
      p, role:admin, applications, *, */*, allow
      p, role:admin, clusters, *, *, allow
      p, role:admin, repositories, *, *, allow
      p, role:admin, certificates, *, *, allow
      p, role:admin, accounts, *, *, allow
      p, role:admin, gpgkeys, *, *, allow
      p, role:admin, logs, *, *, allow
      p, role:admin, exec, *, */*, allow
      p, role:admin, projects, *, *, allow
      
      # Assign admin role to built-in admin user
      g, admin, role:admin
      
      # GitHub user 'timam' gets admin access to tryonmagic project only
      g, timam, proj:tryonmagic:admin
      
      # Default deny policy for OAuth users (not admin)
      p, role:none, *, *, *, deny

    # Default role for OAuth authenticated users (GitHub users)
    policy.default: role:none

    # Scopes to examine for RBAC enforcement
    scopes: '[groups, email]'

server:
  # Server configuration
  extraArgs:
    - --insecure  # Only for development, remove for production

  # Ingress configuration (optional)
  ingress:
    enabled: false
#    ingressClassName: traefik  # or your ingress class
#    hostname: hobbydeployer.timam.dev  # Replace with your domain
#    annotations:
#      cert-manager.io/cluster-issuer: "letsencrypt-prod"  # if using cert-manager
#    tls: true

# Redis configuration
redis:
  enabled: true

# Controller configuration
controller:
  replicas: 1

# Repo server configuration
repoServer:
  replicas: 1

# Application set controller
applicationSet:
  enabled: true