# Simplified ArgoCD configuration with GitHub OAuth
global:
  domain: hobbydeployer.timam.dev

configs:
  cm:
    url: https://hobbydeployer.timam.dev
    admin.enabled: true
    dex.config: |
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: Ov23lieB9Z48UStDROHy
          clientSecret: 0210d8a29107e95c6bdd1e7e45f107b7fdfbcfe9
          orgs:
          - name: tryonmagic

  rbac:
    policy.csv: |
      # Minimal authenticated role with no permissions
      p, role:authenticated, applications, get, */*, deny
      p, role:authenticated, projects, get, *, deny
      p, role:authenticated, repositories, get, *, deny
      p, role:authenticated, clusters, get, *, deny
      
      g, timam, proj:tryonmagic:admin
      
      policy.default: role:authenticated

server:
  extraArgs:
    - --insecure
  ingress:
    enabled: false

redis:
  enabled: true

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  enabled: true