# Simplified ArgoCD configuration with GitHub OAuth
global:
  domain: hobbydeployer.timam.dev

configs:
  cm:
    url: https://hobbydeployer.timam.dev
    admin.enabled: true
    dex.config: |
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: Ov23lieB9Z48UStDROHy
          clientSecret: 0210d8a29107e95c6bdd1e7e45f107b7fdfbcfe9

  rbac:
    policy.csv: |
      g, admin, role:admin
      g, mail@timam.dev, proj:tryonmagic:admin
      g, faisal.ahmedbcse@gmail.com, proj:tryonmagic:admin
      g, mbbipulmandol.cse3.bu@gmail.com, proj:tryonmagic:admin
    scopes: "[email, group]"

server:
  extraArgs:
    - --insecure
  ingress:
    enabled: false

redis:
  enabled: true

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  enabled: true