# Simplified ArgoCD configuration with GitHub OAuth
global:
  domain: hobbydeployer.timam.dev

configs:
  cm:
    url: https://hobbydeployer.timam.dev
    admin.enabled: true
    dex.config: |
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: Ov23lieB9Z48UStDROHy
          clientSecret: 0210d8a29107e95c6bdd1e7e45f107b7fdfbcfe9
          orgs:
          - name: tryonmagic

  rbac:
    policy.csv: |
      # Admin permissions for all ArgoCD resources
      p, role:admin, applications, *, */*, allow
      p, role:admin, clusters, *, *, allow
      p, role:admin, repositories, *, *, allow
      p, role:admin, certificates, *, *, allow
      p, role:admin, accounts, *, *, allow
      p, role:admin, gpgkeys, *, *, allow
      p, role:admin, logs, *, *, allow
      p, role:admin, exec, *, */*, allow
      p, role:admin, projects, *, *, allow
      
      # Readonly permissions for default users
      p, role:readonly, applications, get, */*, allow
      p, role:readonly, logs, get, */*, allow
      
      # Project-specific admin role for tryonmagic
      p, role:proj-tryonmagic-admin, applications, *, tryonmagic/*, allow
      p, role:proj-tryonmagic-admin, repositories, create, tryonmagic, allow
      p, role:proj-tryonmagic-admin, logs, *, tryonmagic/*, allow
      p, role:proj-tryonmagic-admin, exec, *, tryonmagic/*, allow
      p, role:proj-tryonmagic-admin, projects, get, tryonmagic, allow
      
      # Bind GitHub user timam to tryonmagic project admin
      g, timam, role:proj-tryonmagic-admin
      
      # Make tryonmagic org members admins (optional)
      g, tryonmagic:timam, role:admin

server:
  extraArgs:
    - --insecure
  ingress:
    enabled: false

redis:
  enabled: true

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  enabled: true