# ArgoCD configuration with GitHub OAuth authentication
global:
  domain: hobbydeployer.timam.dev

configs:
  cm:
    url: https://hobbydeployer.timam.dev
    application.instanceLabelKey: argocd.argoproj.io/instance
    admin.enabled: true
    dex.config: |
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: Iv23lizfmHBuKOJubMiZ
          clientSecret: 59ddfdfb672541c91193917c69229d7360019926
          redirectURI: https://hobbydeployer.timam.dev/api/dex/callback
          scopes:
            - user:email
            - read:org
            - read:user

  rbac:
    # Default minimal access for authenticated users
    policy.default: role:readonly
    policy.csv: |
      # Built-in admin user - full ArgoCD permissions
      p, role:admin, applications, *, */*, allow
      p, role:admin, clusters, *, *, allow
      p, role:admin, repositories, *, *, allow
      p, role:admin, certificates, *, *, allow
      p, role:admin, accounts, *, *, allow
      p, role:admin, gpgkeys, *, *, allow
      p, role:admin, logs, *, *, allow
      p, role:admin, exec, *, */*, allow
      p, role:admin, projects, *, *, allow
      
      # Readonly role - minimal permissions for default users
      p, role:readonly, applications, get, */*, allow
      p, role:readonly, clusters, get, *, allow
      p, role:readonly, repositories, get, *, allow
      p, role:readonly, logs, get, */*, allow
      
      # User-to-project role bindings
      # Map GitHub users to their project admin roles
      g, timam, proj:tryonmagic:admin
      
      # Add more users as needed:
      # g, <github-username>, proj:<project-name>:admin

    scopes: '[groups, email]'

server:
  extraArgs:
    - --insecure  # Remove for production with proper TLS
  ingress:
    enabled: false

redis:
  enabled: true
controller:
  replicas: 1
repoServer:
  replicas: 1
applicationSet:
  enabled: true