apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/timam/dwt-deployments.git
    targetRevision: main
    path: .
    helm:
      parameters:
        - name: server.extraArgs
          value: '{--insecure}'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true